---
- hosts: worker
  vars_files:
  - ../environment/env_file
  tasks:
  
    - name: Copying token to worker nodes
      copy: src={{ token_file }} dest=join_token

    - name: Reset kubeadm
      shell: |
        kubeadm reset -f

    - name: Joining worker nodes with kubernetes master
      shell: |
        cat join_token | tail -2 > out.sh
        sh out.sh